using System.Globalization;
using System.Text;

namespace AbsCli.Api;

/// <summary>
/// Managed NFC composition. <c>string.Normalize</c> is a silent no-op for
/// non-ASCII input under <c>InvariantGlobalization</c> (issue #97), so the
/// CLI cannot rely on it. Pragmatic subset of UAX #15: singleton mappings,
/// pairwise canonical composition and Hangul — no canonical reordering and
/// no combining-class blocking (.NET exposes no ccc data). Exact for
/// canonically ordered input whose marks all compose; see UnicodeNfcTests
/// for the pinned divergences. Tables live in UnicodeNfc.g.cs, generated by
/// tools/GenerateNfcTables.
/// </summary>
public static partial class UnicodeNfc
{
    private const int SBase = 0xAC00, LBase = 0x1100, VBase = 0x1161, TBase = 0x11A7;
    private const int LCount = 19, VCount = 21, TCount = 28, SCount = LCount * VCount * TCount;

    public static string Compose(string s)
    {
        // Nothing below U+0300 composes or maps (asserted by the generator).
        if (!s.Any(ch => ch >= '\u0300')) return s;
        var output = new List<int>(s.Length);
        int starter = -1;
        foreach (var rune in s.EnumerateRunes())
        {
            var mapped = Singleton(rune.Value);
            if (mapped == null)
            {
                Append(output, ref starter, rune.Value);
                continue;
            }
            foreach (var r in mapped.EnumerateRunes()) Append(output, ref starter, r.Value);
        }
        var sb = new StringBuilder(s.Length);
        foreach (var cp in output) sb.Append(char.ConvertFromUtf32(cp));
        return sb.ToString();
    }

    private static void Append(List<int> output, ref int starter, int cp)
    {
        if (starter >= 0)
        {
            var composed = Combine(output[starter], cp, adjacent: starter == output.Count - 1);
            if (composed >= 0)
            {
                output[starter] = composed;
                return;
            }
        }
        output.Add(cp);
        // Pair-first code points are starters (ccc 0) even when they are
        // spacing vowel signs (Mc), e.g. U+09C7 in U+09CB.
        if (!IsMark(cp) || IsPairFirst(cp)) starter = output.Count - 1;
    }

    private static int Combine(int a, int b, bool adjacent)
    {
        if (adjacent)
        {
            if (a >= LBase && a < LBase + LCount && b >= VBase && b < VBase + VCount)
                return SBase + ((a - LBase) * VCount + (b - VBase)) * TCount;
            if (a >= SBase && a < SBase + SCount && (a - SBase) % TCount == 0 && b > TBase && b < TBase + TCount)
                return a + (b - TBase);
        }
        var i = Array.BinarySearch(PairKeys, ((ulong)a << 21) | (uint)b);
        return i >= 0 ? PairValues[i] : -1;
    }

    private static bool IsPairFirst(int cp)
    {
        var i = ~Array.BinarySearch(PairKeys, (ulong)cp << 21);
        return i < PairKeys.Length && (int)(PairKeys[i] >> 21) == cp;
    }

    private static string? Singleton(int cp)
    {
        var i = Array.BinarySearch(SingletonKeys, cp);
        return i >= 0 ? SingletonValues[i] : null;
    }

    private static bool IsMark(int cp) =>
        Rune.GetUnicodeCategory(new Rune(cp)) is UnicodeCategory.NonSpacingMark
            or UnicodeCategory.SpacingCombiningMark or UnicodeCategory.EnclosingMark;
}
