using System.Text.Json.Serialization;
using AbsCli.Configuration;

namespace AbsCli.Models;

[JsonSerializable(typeof(AppConfig))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(LibraryListResponse))]
[JsonSerializable(typeof(Library))]
[JsonSerializable(typeof(PaginatedResponse))]
[JsonSerializable(typeof(LibraryItemMinified))]
[JsonSerializable(typeof(BookMediaMinified))]
[JsonSerializable(typeof(LibraryItemExpanded))]
[JsonSerializable(typeof(LibraryFile))]
[JsonSerializable(typeof(LibraryFileMetadata))]
[JsonSerializable(typeof(PodcastMedia))]
[JsonSerializable(typeof(SearchResult))]
[JsonSerializable(typeof(UpdateMediaResponse))]
[JsonSerializable(typeof(BatchUpdateResponse))]
[JsonSerializable(typeof(BatchGetResponse))]
[JsonSerializable(typeof(SeriesItem))]
[JsonSerializable(typeof(AuthorItem))]
[JsonSerializable(typeof(AuthorMatchRequest))]
[JsonSerializable(typeof(AuthorMatchResponse))]
[JsonSerializable(typeof(AuthorUpdateResponse))]
[JsonSerializable(typeof(AuthorImageRequest))]
[JsonSerializable(typeof(AuthorImageResponse))]
[JsonSerializable(typeof(BackupItem))]
[JsonSerializable(typeof(BackupListResponse))]
[JsonSerializable(typeof(ScanResult))]
[JsonSerializable(typeof(TaskItem))]
[JsonSerializable(typeof(TaskListResponse))]
[JsonSerializable(typeof(ProviderEntry))]
[JsonSerializable(typeof(MetadataProviderGroups))]
[JsonSerializable(typeof(MetadataProvidersResponse))]
[JsonSerializable(typeof(CoverSearchResponse))]
[JsonSerializable(typeof(CoverApplyResponse))]
[JsonSerializable(typeof(CoverApplyByUrlRequest))]
[JsonSerializable(typeof(CoverLinkExistingRequest))]
[JsonSerializable(typeof(CoverFileSavedDescriptor))]
[JsonSerializable(typeof(EncodeM4bOptions))]
[JsonSerializable(typeof(EncodeM4bStartReceipt))]
[JsonSerializable(typeof(AudnexusChapter))]
[JsonSerializable(typeof(ChaptersLookupResponse))]
[JsonSerializable(typeof(ChaptersLookupError))]
[JsonSerializable(typeof(ChapterWriteEntry))]
[JsonSerializable(typeof(ChaptersSetRequest))]
[JsonSerializable(typeof(ChaptersSetResponse))]
[JsonSerializable(typeof(EmbedMetadataOptions))]
[JsonSerializable(typeof(EmbedMetadataReceipt))]
[JsonSerializable(typeof(BatchEmbedMetadataRequest))]
[JsonSerializable(typeof(BatchEmbedMetadataReceipt))]
[JsonSerializable(typeof(EbookFileStatusReceipt))]
[JsonSerializable(typeof(UploadManifestEntry))]
[JsonSerializable(typeof(UploadReceipt))]
[JsonSerializable(typeof(List<UploadManifestEntry>))]
[JsonSerializable(typeof(Collection))]
[JsonSerializable(typeof(RssFeed))]
[JsonSerializable(typeof(CollectionCreateRequest))]
[JsonSerializable(typeof(CollectionBooksRequest))]
[JsonSerializable(typeof(CollectionBookRequest))]
[JsonSerializable(typeof(MediaProgress))]
[JsonSerializable(typeof(ProgressUpdateRequest))]
[JsonSourceGenerationOptions(WriteIndented = true)]
public partial class AppJsonContext : JsonSerializerContext;

public class LoginRequest
{
    [JsonPropertyName("username")]
    public string Username { get; set; } = "";

    [JsonPropertyName("password")]
    public string Password { get; set; } = "";
}
