// <auto-generated>
//   Generated by tools/GenerateResponseExamples.
//   Do not edit by hand — run `dotnet run --project tools/GenerateResponseExamples -- <path>`.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace AbsCli.Commands;

internal static class ResponseExamples
{
    private static readonly Dictionary<Type, string> Samples = new()
    {
        { typeof(AbsCli.Models.AuthorItem),
          "{\n  \"id\": \"<string>\",\n  \"asin\": null,\n  \"name\": \"<string>\",\n  \"description\": null,\n  \"imagePath\": null,\n  \"libraryId\": \"<string>\",\n  \"addedAt\": 0,\n  \"updatedAt\": 0,\n  \"numBooks\": 0,\n  \"lastFirst\": null\n}" },
        { typeof(AbsCli.Models.AuthorListResponse),
          "{\n  \"authors\": [\n    {\n      \"id\": \"<string>\",\n      \"asin\": null,\n      \"name\": \"<string>\",\n      \"description\": null,\n      \"imagePath\": null,\n      \"libraryId\": \"<string>\",\n      \"addedAt\": 0,\n      \"updatedAt\": 0,\n      \"numBooks\": 0,\n      \"lastFirst\": null\n    }\n  ]\n}" },
        { typeof(AbsCli.Models.BackupItem),
          "{\n  \"id\": \"<string>\",\n  \"backupDirPath\": null,\n  \"datePretty\": null,\n  \"fullPath\": null,\n  \"path\": null,\n  \"filename\": null,\n  \"fileSize\": 0,\n  \"createdAt\": 0,\n  \"serverVersion\": null\n}" },
        { typeof(AbsCli.Models.BackupListResponse),
          "{\n  \"backups\": [\n    {\n      \"id\": \"<string>\",\n      \"backupDirPath\": null,\n      \"datePretty\": null,\n      \"fullPath\": null,\n      \"path\": null,\n      \"filename\": null,\n      \"fileSize\": 0,\n      \"createdAt\": 0,\n      \"serverVersion\": null\n    }\n  ],\n  \"backupLocation\": null,\n  \"backupPathEnvSet\": false\n}" },
        { typeof(AbsCli.Models.BatchGetResponse),
          "{\n  \"libraryItems\": [\n    {}\n  ]\n}" },
        { typeof(AbsCli.Models.BatchUpdateResponse),
          "{\n  \"success\": false,\n  \"updates\": 0\n}" },
        { typeof(AbsCli.Models.CoverSearchResponse),
          "{\n  \"results\": [\n    \"<string>\"\n  ]\n}" },
        { typeof(AbsCli.Models.Library),
          "{\n  \"id\": \"<string>\",\n  \"name\": \"<string>\",\n  \"folders\": [\n    {\n      \"id\": \"<string>\",\n      \"fullPath\": \"<string>\",\n      \"libraryId\": \"<string>\",\n      \"addedAt\": 0\n    }\n  ],\n  \"displayOrder\": 0,\n  \"icon\": null,\n  \"mediaType\": \"<string>\",\n  \"provider\": null,\n  \"lastScan\": 0,\n  \"lastScanVersion\": null,\n  \"createdAt\": 0,\n  \"lastUpdate\": 0\n}" },
        { typeof(AbsCli.Models.LibraryItemMinified),
          "{\n  \"id\": \"<string>\",\n  \"ino\": null,\n  \"libraryId\": \"<string>\",\n  \"folderId\": null,\n  \"path\": null,\n  \"relPath\": null,\n  \"isFile\": false,\n  \"mtimeMs\": 0,\n  \"ctimeMs\": 0,\n  \"birthtimeMs\": 0,\n  \"addedAt\": 0,\n  \"updatedAt\": 0,\n  \"isMissing\": false,\n  \"isInvalid\": false,\n  \"mediaType\": \"<string>\",\n  \"media\": {},\n  \"numFiles\": 0,\n  \"size\": 0\n}" },
        { typeof(AbsCli.Models.LibraryListResponse),
          "{\n  \"libraries\": [\n    {\n      \"id\": \"<string>\",\n      \"name\": \"<string>\",\n      \"folders\": [\n        {\n          \"id\": \"<string>\",\n          \"fullPath\": \"<string>\",\n          \"libraryId\": \"<string>\",\n          \"addedAt\": 0\n        }\n      ],\n      \"displayOrder\": 0,\n      \"icon\": null,\n      \"mediaType\": \"<string>\",\n      \"provider\": null,\n      \"lastScan\": 0,\n      \"lastScanVersion\": null,\n      \"createdAt\": 0,\n      \"lastUpdate\": 0\n    }\n  ]\n}" },
        { typeof(AbsCli.Models.LoginResponse),
          "{\n  \"user\": {\n    \"id\": \"<string>\",\n    \"username\": \"<string>\",\n    \"type\": \"<string>\",\n    \"token\": null,\n    \"isActive\": false,\n    \"accessToken\": null,\n    \"refreshToken\": null,\n    \"permissions\": {\n      \"download\": false,\n      \"update\": false,\n      \"delete\": false,\n      \"upload\": false,\n      \"accessAllLibraries\": false,\n      \"accessAllTags\": false,\n      \"accessExplicitContent\": false\n    }\n  },\n  \"userDefaultLibraryId\": null,\n  \"serverSettings\": {\n    \"version\": null,\n    \"buildNumber\": 0\n  }\n}" },
        { typeof(AbsCli.Models.MetadataProviderGroups),
          "{\n  \"books\": [\n    {\n      \"value\": \"<string>\",\n      \"text\": \"<string>\"\n    }\n  ],\n  \"booksCovers\": [\n    {\n      \"value\": \"<string>\",\n      \"text\": \"<string>\"\n    }\n  ],\n  \"podcasts\": [\n    {\n      \"value\": \"<string>\",\n      \"text\": \"<string>\"\n    }\n  ]\n}" },
        { typeof(AbsCli.Models.MetadataProvidersResponse),
          "{\n  \"providers\": {\n    \"books\": [\n      {\n        \"value\": \"<string>\",\n        \"text\": \"<string>\"\n      }\n    ],\n    \"booksCovers\": [\n      {\n        \"value\": \"<string>\",\n        \"text\": \"<string>\"\n      }\n    ],\n    \"podcasts\": [\n      {\n        \"value\": \"<string>\",\n        \"text\": \"<string>\"\n      }\n    ]\n  }\n}" },
        { typeof(AbsCli.Models.PaginatedResponse),
          "{\n  \"results\": [\n    {}\n  ],\n  \"total\": 0,\n  \"limit\": 0,\n  \"page\": 0\n}" },
        { typeof(AbsCli.Models.ProviderEntry),
          "{\n  \"value\": \"<string>\",\n  \"text\": \"<string>\"\n}" },
        { typeof(AbsCli.Models.ScanResult),
          "{\n  \"result\": \"<string>\"\n}" },
        { typeof(AbsCli.Models.SearchResult),
          "{\n  \"book\": [\n    {}\n  ],\n  \"podcast\": [\n    {}\n  ],\n  \"narrators\": [\n    {}\n  ],\n  \"tags\": [\n    {}\n  ],\n  \"genres\": [\n    {}\n  ],\n  \"series\": [\n    {}\n  ],\n  \"authors\": [\n    {}\n  ]\n}" },
        { typeof(AbsCli.Models.SeriesItem),
          "{\n  \"id\": \"<string>\",\n  \"name\": \"<string>\",\n  \"nameIgnorePrefix\": null,\n  \"description\": null,\n  \"addedAt\": 0,\n  \"updatedAt\": 0,\n  \"libraryId\": \"<string>\"\n}" },
        { typeof(AbsCli.Models.TaskItem),
          "{\n  \"id\": \"<string>\",\n  \"action\": null,\n  \"title\": null,\n  \"description\": null,\n  \"error\": null,\n  \"isFailed\": false,\n  \"isFinished\": false,\n  \"showSuccess\": false,\n  \"startedAt\": 0,\n  \"finishedAt\": 0,\n  \"data\": {}\n}" },
        { typeof(AbsCli.Models.TaskListResponse),
          "{\n  \"tasks\": [\n    {\n      \"id\": \"<string>\",\n      \"action\": null,\n      \"title\": null,\n      \"description\": null,\n      \"error\": null,\n      \"isFailed\": false,\n      \"isFinished\": false,\n      \"showSuccess\": false,\n      \"startedAt\": 0,\n      \"finishedAt\": 0,\n      \"data\": {}\n    }\n  ]\n}" },
        { typeof(AbsCli.Models.UpdateMediaResponse),
          "{\n  \"updated\": false,\n  \"libraryItem\": {}\n}" },
    };

    public static string For(Type type)
        => Samples.TryGetValue(type, out var sample) ? sample : throw new KeyNotFoundException($"No response example registered for {type.FullName}");

    public static IReadOnlyDictionary<Type, string> All => Samples;
}
