services:
  audiobookshelf:
    image: advplyr/audiobookshelf:2.33.2
    ports:
      - "13378:80"
    volumes:
      - abs-config:/config
      - abs-metadata:/metadata
    environment:
      - PORT=80

volumes:
  abs-config:
  abs-metadata:
