// Emits src/AbsCli/Api/UnicodeNfc.g.cs from the host's ICU. Run manually:
//   dotnet run --project tools/GenerateNfcTables -- src/AbsCli/Api/UnicodeNfc.g.cs
// Not wired into the build: output depends on the host ICU's Unicode version.
using System.Globalization;
using System.Text;

if (args.Length != 1)
{
    Console.Error.WriteLine("usage: GenerateNfcTables <output.g.cs>");
    return 1;
}
if ("o\u0308".Normalize(NormalizationForm.FormC) != "\u00f6")
{
    Console.Error.WriteLine("ICU normalization unavailable (invariant globalization?)");
    return 1;
}

var pairs = new SortedDictionary<ulong, int>();
var singletons = new SortedDictionary<int, string>();
for (int cp = 0; cp <= 0x10FFFF; cp++)
{
    if (cp is >= 0xD800 and <= 0xDFFF) continue;
    // Hangul syllables compose arithmetically in UnicodeNfc.Combine.
    if (cp is >= 0xAC00 and <= 0xD7A3) continue;
    // U+FFFE rejects FormC on this runtime's ICU binding even though it's a
    // valid (if reserved) scalar value with no canonical mapping either way.
    if (cp == 0xFFFE) continue;
    var c = char.ConvertFromUtf32(cp);
    var nfc = c.Normalize(NormalizationForm.FormC);
    if (nfc != c)
    {
        singletons[cp] = nfc;
        continue;
    }
    var d = Runes(c.Normalize(NormalizationForm.FormD));
    if (d.Count < 2) continue;
    var last = d[^1];
    var prefix = Runes(string.Concat(d.Take(d.Count - 1)).Normalize(NormalizationForm.FormC));
    if (prefix.Count != 1) continue;
    if ((prefix[0] + last).Normalize(NormalizationForm.FormC) != c) continue;
    pairs[((ulong)char.ConvertToUtf32(prefix[0], 0) << 21) | (uint)char.ConvertToUtf32(last, 0)] = cp;
}

// Backs UnicodeNfc.Compose's fast path (every char < U+0300 is left alone).
foreach (var key in pairs.Keys)
{
    if ((key & 0x1FFFFF) < 0x300) throw new InvalidOperationException($"pair second element below U+0300: {key:X}");
}
foreach (var key in singletons.Keys)
{
    if (key < 0x300) throw new InvalidOperationException($"singleton below U+0300: {key:X4}");
}

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("// Generated by tools/GenerateNfcTables from ICU. Do not edit by hand.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace AbsCli.Api;");
sb.AppendLine();
sb.AppendLine("public static partial class UnicodeNfc");
sb.AppendLine("{");
AppendArray(sb, "ulong", "PairKeys", pairs.Keys.Select(k => $"0x{k:X}UL"));
sb.AppendLine();
AppendArray(sb, "int", "PairValues", pairs.Values.Select(v => $"0x{v:X}"));
sb.AppendLine();
AppendArray(sb, "int", "SingletonKeys", singletons.Keys.Select(k => $"0x{k:X}"));
sb.AppendLine();
AppendArray(sb, "string", "SingletonValues", singletons.Values.Select(Escape));
sb.AppendLine("}");
File.WriteAllText(args[0], sb.ToString().TrimEnd() + "\n");
Console.Error.WriteLine($"{pairs.Count} pairs, {singletons.Count} singletons -> {args[0]}");
return 0;

static List<string> Runes(string s) => s.EnumerateRunes().Select(r => r.ToString()).ToList();

static string Escape(string s) =>
    "\"" + string.Concat(s.EnumerateRunes().Select(r =>
        r.Value > 0xFFFF ? $"\\U{r.Value:X8}" : $"\\u{r.Value:X4}")) + "\"";

static void AppendArray(StringBuilder sb, string type, string name, IEnumerable<string> items)
{
    sb.AppendLine($"    private static readonly {type}[] {name} =");
    sb.AppendLine("    [");
    foreach (var chunk in items.Chunk(8))
    {
        sb.AppendLine("        " + string.Join(", ", chunk) + ",");
    }
    sb.AppendLine("    ];");
}
